### PR TITLE
add all the redactor settings

### PR DESCRIPTION
**Pull request by davekaro**
I wanted the option to add `plugins` setting, and figured I'd add them all. I copied the settings directly from the latest redactor source (v10.0.7). I noticed a few differences, mainly `buttonSource` renamed to `source` and `convertImagesLinks` renamed to `convertImageLinks` - interestingly the Redactor docs still reference the old names. Also - I didn't add tests for all the new settings yet, wanted to run this by you first. It seems some of the defaults changed since you wrote the tests, so if you want them all updated, let me know.

### CODE REVIEW

**Comment by davekaro** [comment]
Crap I just started trying this out in my app and nothing is working. Will update if needed.

**Comment by davekaro** [comment]
Ok it works now. Should have listened to the `// privates` comment better

**Comment by omghax** [comment]
Hey @davekaro, thanks for the PR. Sorry it's taken me this long to reply.

I'm not entirely sold on supporting every setting, since I haven't vetted them all to ensure they don't misbehave in an Ember app. That being said, I just pushed 1.0.0-beta.2, which defines `redactorCallbacks` and `redactorSettings` as [concatenated properties](http://emberjs.com/api/classes/Ember.CoreObject.html#property_concatenatedProperties), so you can more easily add them in your app, like so:

``` javascript
import IvyRedactorComponent from 'ivy-redactor/components/ivy-redactor';

export default IvyRedactorComponent.extend({
  redactorCallbacks: ['initCallback'],
  redactorSettings: ['activeButtons'],

  activeButtons: ['italic', 'bold'],

  initCallback: function() {
    // do some stuff here
  }
});
```

These callbacks and settings will be merged with the ones defined in the library. Does that work for you? If there are some options that you think merit being included in the base library I'm not opposed to adding them.

Let me know what you think.

**Comment by davekaro** [comment]
I think the concatenated properties is perfect! Thanks for adding that.

**Pull request closed without merging**
